type = "settings"
id = "main"
title = "Aquarium example"
description = "An example for Aquarium"
url = "https://aquarium.netlify.app/"
copyright = "2021, Arnau Siches"
navigation = [
  "notes",
  "sketches",
  "bulletins",
  "projects",
]

[licence]
url = "http://creativecommons.org/licenses/by-nc/4.0/"
name = "Creative Commons Attribution-NonCommercial 4.0 International License"
